### ISSUE TITLE
game 페이지 JavaScript 기능 추가

### ISSUE THREAD

**Issue by inhwalee** [014ee/dice-game#2]
## Tasks
game.html 에서 아래 기능을 구현해야 합니다.

- [x] 스타트 버튼을 누르면 참여자와 컴퓨터에 1~6까지의 숫자 중 하나가 랜덤으로 할당된다.
- [x] 중복되는 숫자가 나오는 경우 다시 할당된다.
- [x] 할당된 후에는 result.html로 이동한다.
